version: "3.9"
services:
  api:
    build:
      context: ./APIDevelopment
      dockerfile: Dockerfile

    ports:
      - "8000:8000"
    volumes:
      - C:/Users/kumud/PycharmProjects/StackingAlgo/APIDevelopment:/app
    command: ["uvicorn", "model_app:app", "--host", "0.0.0.0", "--port", "8000"]